//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TF2CrowdControl.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UserText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TF2CrowdControl.Resources.UserText", typeof(UserText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Special thanks to {2}.
        /// </summary>
        public static string EffectHypeTrain_Format {
            get {
                return ResourceManager.GetString("EffectHypeTrain_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1} {2}).
        /// </summary>
        public static string EffectHypeTrainContributor_Format {
            get {
                return ResourceManager.GetString("EffectHypeTrainContributor_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level {0} Hype Train!.
        /// </summary>
        public static string EffectHypeTrainLevel_Format {
            get {
                return ResourceManager.GetString("EffectHypeTrainLevel_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} bits makes {1} towards {2}..
        /// </summary>
        public static string EffectHypeTrainProgress_Format {
            get {
                return ResourceManager.GetString("EffectHypeTrainProgress_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Configs.
        /// </summary>
        public static string InstallConfigs {
            get {
                return ResourceManager.GetString("InstallConfigs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  and the configs must be installed.  If any of the above settings are changed, TF2 must be closed and reopened..
        /// </summary>
        public static string LaunchOptions_After {
            get {
                return ResourceManager.GetString("LaunchOptions_After", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For the RCON connection to work with this app, TF2&apos;s Launch Options must include .
        /// </summary>
        public static string LaunchOptions_Before {
            get {
                return ResourceManager.GetString("LaunchOptions_Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crowd Control connection ended..
        /// </summary>
        public static string Log_CCConnectionEnd {
            get {
                return ResourceManager.GetString("Log_CCConnectionEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crowd Control connect failed - retrying..
        /// </summary>
        public static string Log_CCConnectionException {
            get {
                return ResourceManager.GetString("Log_CCConnectionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crowd Control game Update failed..
        /// </summary>
        public static string Log_CCEffectGameUpdateException {
            get {
                return ResourceManager.GetString("Log_CCEffectGameUpdateException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crowd Control Request Parse failed..
        /// </summary>
        public static string Log_CCEffectInvokeParseFail {
            get {
                return ResourceManager.GetString("Log_CCEffectInvokeParseFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crowd Control OnRequestReceived failed..
        /// </summary>
        public static string Log_CCEffectOnRequestReceivedException {
            get {
                return ResourceManager.GetString("Log_CCEffectOnRequestReceivedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} effect [{1}]. {2}.
        /// </summary>
        public static string Log_CCEffectResponder_Format {
            get {
                return ResourceManager.GetString("Log_CCEffectResponder_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respond to effect request failed..
        /// </summary>
        public static string Log_CCEffectResponderException {
            get {
                return ResourceManager.GetString("Log_CCEffectResponderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status response for effect {} failed..
        /// </summary>
        public static string Log_CCEffectResponderStatusException_Format {
            get {
                return ResourceManager.GetString("Log_CCEffectResponderStatusException_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respond to Crowd Control effect response failed..
        /// </summary>
        public static string Log_CCEffectResponseException {
            get {
                return ResourceManager.GetString("Log_CCEffectResponseException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crowd Control effect Update failed..
        /// </summary>
        public static string Log_CCEffectUpdateException {
            get {
                return ResourceManager.GetString("Log_CCEffectUpdateException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crowd Control KeepAlive failed..
        /// </summary>
        public static string Log_CCKeepAliveException {
            get {
                return ResourceManager.GetString("Log_CCKeepAliveException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crowd Control Listen failed..
        /// </summary>
        public static string Log_CCListenException {
            get {
                return ResourceManager.GetString("Log_CCListenException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crowd Control OnConnected failed..
        /// </summary>
        public static string Log_CCOnConnectException {
            get {
                return ResourceManager.GetString("Log_CCOnConnectException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hype Train Event: {0} {1} {2}.
        /// </summary>
        public static string Log_EffectHypeTrain_Format {
            get {
                return ResourceManager.GetString("Log_EffectHypeTrain_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported Effect Request Type: {0}.
        /// </summary>
        public static string Log_EffectRequestTypeUnknown_Format {
            get {
                return ResourceManager.GetString("Log_EffectRequestTypeUnknown_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effect {0} not found. .
        /// </summary>
        public static string Log_EffectTestNotFound_Format {
            get {
                return ResourceManager.GetString("Log_EffectTestNotFound_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configured {0}.
        /// </summary>
        public static string Log_InstallConfig {
            get {
                return ResourceManager.GetString("Log_InstallConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure while installing configuration - connection with TF2 may not work..
        /// </summary>
        public static string Log_InstallConfigsException {
            get {
                return ResourceManager.GetString("Log_InstallConfigsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No TF2 connection yet..
        /// </summary>
        public static string Log_NoTF2Connection {
            get {
                return ResourceManager.GetString("Log_NoTF2Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading TF2Config..
        /// </summary>
        public static string Log_TF2ConfigLoadException {
            get {
                return ResourceManager.GetString("Log_TF2ConfigLoadException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving TF2Config..
        /// </summary>
        public static string Log_TF2ConfigSaveException {
            get {
                return ResourceManager.GetString("Log_TF2ConfigSaveException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed Connection to TF2. Change port/password/path settings (or restart this app) to try again..
        /// </summary>
        public static string Log_TF2ConnectionException {
            get {
                return ResourceManager.GetString("Log_TF2ConnectionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RCON password:.
        /// </summary>
        public static string RCONPassword_Label {
            get {
                return ResourceManager.GetString("RCONPassword_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anything is fine - this is just local on your machine.
        /// </summary>
        public static string RCONPassword_ToolTip {
            get {
                return ResourceManager.GetString("RCONPassword_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RCON port:.
        /// </summary>
        public static string RCONPort_Label {
            get {
                return ResourceManager.GetString("RCONPort_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any number typically between 40000 and 49000 - this is just local on your machine.
        /// </summary>
        public static string RCONPort_ToolTip {
            get {
                return ResourceManager.GetString("RCONPort_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status | .
        /// </summary>
        public static string Status_Before {
            get {
                return ResourceManager.GetString("Status_Before", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crowd Control connection.
        /// </summary>
        public static string Status_CC {
            get {
                return ResourceManager.GetString("Status_CC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  | .
        /// </summary>
        public static string Status_CC_After {
            get {
                return ResourceManager.GetString("Status_CC_After", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   .
        /// </summary>
        public static string Status_ClassName_After {
            get {
                return ResourceManager.GetString("Status_ClassName_After", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   .
        /// </summary>
        public static string Status_MapName_After {
            get {
                return ResourceManager.GetString("Status_MapName_After", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TF2 connection.
        /// </summary>
        public static string Status_TF2 {
            get {
                return ResourceManager.GetString("Status_TF2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  | .
        /// </summary>
        public static string Status_TF2_After {
            get {
                return ResourceManager.GetString("Status_TF2_After", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TF2 Path:.
        /// </summary>
        public static string TF2Path_Label {
            get {
                return ResourceManager.GetString("TF2Path_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path of the folder that contains tf2_win64.exe.
        /// </summary>
        public static string TF2Path_ToolTip {
            get {
                return ResourceManager.GetString("TF2Path_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Fortress 2 Settings.
        /// </summary>
        public static string TF2Settings {
            get {
                return ResourceManager.GetString("TF2Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TF2 Spectator for Crowd Control - {0}.{1}.{2} - by {3}.
        /// </summary>
        public static string WindowTitle_Format {
            get {
                return ResourceManager.GetString("WindowTitle_Format", resourceCulture);
            }
        }
    }
}
